### ISSUE TITLE
Is import supported?

### ISSUE THREAD

**Issue by pbuckley4192** [bmustiata/jenny#59]
Got this error trying to run a basic declarative pipeline.. I have to do an import to get the test results for a nonCPS method...

Is this supported?

```
/Jenkinsfile: 1: unable to resolve class hudson.tasks.test.AbstractTestResultAction
 @ line 1, column 1.
   import hudson.tasks.test.AbstractTestResultAction
   ^

1 error
```

**Comment by bmustiata** [comment]
I would need to see some small sample.

If it's something that is reusable and would be a good idea to have it in the core, maybe yes. There is only one exception currently, and that's an exception https://github.com/bmustiata/jenny/blob/master/mocks/hudson/AbortException.groovy that jenny would never throw anyway. As you can see this means coding them by hand. Coding them by hand != fun.

If creating custom actions is needed, it seems it would be a good idea to have it there, but it would also mean there is probably also required some wiring that can bring the custom actions into the jenny global context. (extending classpath, classpath scanning, registering actions)

Since I'm not a big fan of custom java actions - I'm using groovy shared libraries all around, with a lot of custom commands - I won't spend a lot of effort into it, but I'm willing to merge any PR in that direction.

**Comment by pbuckley4192** [comment]
Ok, Thank you both so much!! 
Closing the issue now that I have my answer. :+1:
